version: "3.8"

services:
    webapp:
        build: ./react-ui
        image: tweetsearch-ui:latest
        volumes:
            - ./react-ui:/usr/bin/tweetsearch/ui
    server:
        build: ./
        image: tweetsearch-server:latest
        volumes:
            - .:/usr/bin/tweetsearch/server